#百层试炼作弊

hostname = example.com, baidu.com

^https\:\/\/example\.com\/resource1\/3 url script-request-header https://raw.githubusercontent.com/gfk-sveyigey/ProxyConfig/refs/heads/main/fakebc.js

^https\:\/\/www\.baidu\.com url script-response-body https://raw.githubusercontent.com/gfk-sveyigey/ProxyConfig/refs/heads/main/fakebc.js

