#百层试炼作弊

hostname = poster-api.xd.cn

https\:\/\/poster-api\.xd\.cn\/api\/v1\.0\/cdk\/game\/submit-simple url script-response-body https://raw.githubusercontent.com/gfk-sveyigey/ProxyConfig/refs/heads/main/fakebc.js
