#百层试炼作弊

hostname = poster-api.xd.cn

^https?://poster-api\.xd\.cn/api/v1\.0/cdk/game/submit-simple url script-analyze-echo-response bc.js

^https?://poster-api\.xd\.cn/direction url script-request-header bc.js

^https?://poster-api\.xd\.cn/fake url script-analyze-echo-response bc.js
